# Format Configuration with Time Inline after Directory
format = "$username$directory$time\n$character"

right_format = "$git_status$git_branch"

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Disable the blank line at the start of the prompt
add_newline = true

[line_break]
disabled = true

[time]
format = "[ $time](fg:#000000 bg:#a6e3a1)[](fg:#a6e3a1 bg:none)"
style = "bold"
utc_time_offset = "+1"
time_format = "%H:%M"
disabled = false


[character]
success_symbol = "\n[❯](fg:#fab387 bold)"  # Orange for success
error_symbol = "\n[❯](fg:#f38ba8)"         # Bright red for errors

[hostname]
ssh_only = true
format = "[$hostname](bold fg:#89dceb)"    # Light blue for hostname
disabled = false

[username]
format = "(fg:#1e1e2e bg:#1e1e2e)[](fg:#74c7ec bg:#1e1e2e)[ $user](fg:#1e1e2e bg:#74c7ec)[](fg:#74c7ec bg:#fab387)"
style_user = "bold cyan"  # Cyan accent on username
show_always = true

[directory]
format = "(fg:#fab387 bg:#fab387)[  $path](fg:#1e1e2e bg:#fab387)[](fg:#fab387 bg:#a6e3a1)"
style = "fg:#f9e2af bg:#1e1e2e" # Warm yellow in directory
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = "(fg:#1e1e2e bg:#1e1e2e)[](fg:#f9e2af bg:#1e1e2e)[ $branch](fg:#131729 bg:#f9e2af)[](fg:#f9e2af bg:none)"
style = "fg:#d9d7d6 bg:#1e1e2e" # Yellow for git branch

[git_status]
format = "(fg:#1e1e2e bg:#1e1e2e)[](fg:#a6e3a1 bg:#1e1e2e)[ $all_status](fg:#1e1e2e bg:#a6e3a1)[](fg:#a6e3a1 bg:none)"
style = "fg:#d9d7d6 bg:#1e1e2e" # Green for git status
conflicted = "="
ahead = "${count}"
behind = "${count}"
diverged = "${ahead_count}${behind_count}"
up_to_date = ""
untracked = "?${count}"
stashed = ""
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "${count}"

[package]
disabled = true


[python]
symbol = " "
format = '[($symbol $virtualenv)]($style)|[ Z ]($style)'  # Show environment or "Z"
style = "yellow bold"
disabled = false

