# Aliases go here
alias nano='nvim'
alias 'nvim /'='sudo nvim '
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias yay='yay --color=always'
alias pacman='pacman --color=auto'
alias hyprpaper='hyprpaper -c ~/.config/hypr/hyprpaper/hyprpaper.conf'
alias clear='clear && printf "\033c"'
alias hyprconfig='nvim ~/.config/hypr/hyprland.conf'
alias pip='pip --require-virtualenv'
alias cat='bat'
