$primary_paletteKeyColor = aa6174
$secondary_paletteKeyColor = 906f75
$tertiary_paletteKeyColor = 966f49
$neutral_paletteKeyColor = 817476
$neutral_variant_paletteKeyColor = 847376
$background = 191113
$onBackground = efdee0
$surface = 191113
$surfaceDim = 191113
$surfaceBright = 413738
$surfaceContainerLowest = 140c0e
$surfaceContainerLow = 22191b
$surfaceContainer = 261d1f
$surfaceContainerHigh = 312829
$surfaceContainerHighest = 3c3234
$onSurface = efdee0
$surfaceVariant = 514346
$onSurfaceVariant = d6c2c5
$inverseSurface = efdee0
$inverseOnSurface = 382e30
$outline = 9e8c8f
$outlineVariant = 514346
$shadow = 000000
$scrim = 000000
$surfaceTint = ffb1c3
$primary = ffb1c3
$onPrimary = 551d2e
$primaryContainer = 713344
$onPrimaryContainer = ffd9e0
$inversePrimary = 8d4a5b
$secondary = e4bdc4
$onSecondary = 43292f
$secondaryContainer = 60444a
$onSecondaryContainer = ffd9e0
$tertiary = edbe92
$onTertiary = 462a09
$tertiaryContainer = b28960
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = ffd9e0
$primaryFixedDim = ffb1c3
$onPrimaryFixed = 3a0719
$onPrimaryFixedVariant = 713344
$secondaryFixed = ffd9e0
$secondaryFixedDim = e4bdc4
$onSecondaryFixed = 2b151b
$onSecondaryFixedVariant = 5b3f45
$tertiaryFixed = ffdcbe
$tertiaryFixedDim = edbe92
$onTertiaryFixed = 2c1600
$onTertiaryFixedVariant = 60401e
$term0 = 353434
$term1 = ff4e7d
$term2 = ffbbb3
$term3 = ffdedd
$term4 = b3a2d5
$term5 = ec8faa
$term6 = ffba93
$term7 = efd1d0
$term8 = b49e9d
$term9 = ff829a
$term10 = ffd3cd
$term11 = fff1f0
$term12 = dcbc93
$term13 = fba8bc
$term14 = ffd1c0
$term15 = ffffff
$rosewater = ffedee
$flamingo = fdd9de
$pink = ffd1de
$mauve = ffa5ce
$red = fe94b0
$maroon = f5aaba
$peach = ffbdc1
$yellow = ffedec
$green = ffd8c5
$teal = dedcff
$sky = ebd1ff
$sapphire = f2b2f2
$blue = f7a2d9
$lavender = ffb8de
$klink = bb6da7
$klinkSelection = bb6ca6
$kvisited = c75c8d
$kvisitedSelection = c85c8c
$knegative = ea4f7b
$knegativeSelection = ea4f7a
$kneutral = ff8693
$kneutralSelection = ff8692
$kpositive = fd8c2a
$kpositiveSelection = fd8c2a
$text = efdee0
$subtext1 = d6c2c5
$subtext0 = 9e8c8f
$overlay2 = 8a7a7c
$overlay1 = 766769
$overlay0 = 635658
$surface2 = 514547
$surface1 = 3f3437
$surface0 = 2c2225
$base = 191113
$mantle = 191113
$crust = 181012
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
