#######################################
### INTERACTIVE WINDOW RULES ###
#######################################

# Border color variables for floating windows
$border_inactive          = rgb(005577) #rgb(003355)
$floating_border_active   = rgb(00d4ff) #rgb(0085e6)
$pinned_border_active     = rgb(B98578) #rgb(9F808B)
# Floating window border colors
#windowrulev2 = bordercolor $floating_border_active $border_inactive, floating:1
windowrulev2 = bordercolor $pinned_border_active $border_inactive, pinned:1
