###########################
# AUTOSTART APPLICATIONS
###########################

exec-once = spotify
exec-once = /home/bandit/.local/bin/launch-caelestia
exec-once = systemctl --user start hyprpolkitagent
exec-once = hyprctl dispatch workspace 1
exec-once = clipse -listen

# Corners getting rounded using GTK (disabled - Using caelestia)
#exec = python ~/.config/hypr/scripts/roundmask.py

# Wallpaper
exec-once = awww-daemon --format xrgb

# Update DBus activation environment for Wayland
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = ~/.local/bin/zen-pseudo-manager
exec-once = ~/.local/bin/zen-pip-place
exec-once = ~/.local/bin/hypr-session daemon
exec-once = ~/.local/bin/hypr-session prompt
exec-once = ~/.local/bin/hypr-game-caps-watcher
